name: Run Script

on:
  workflow_dispatch:
  push: # Add this line to trigger the workflow on push
  schedule:
    - cron: '0 */12 * * *' # Run twice daily

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python company-cron.py
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
