name: Run Python script

on:
  schedule:
    - cron: '0 */12 * * *'  # This will run the action every 12 hours

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have any dependencies, install them here
        # For example: pip install psycopg2-binary

    - name: Run script
      run: python company-cron.py
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
