name: Run Python script twice daily

on:
  push:
  schedule:
    - cron: '0 0,12 * * *' # Run at 00:00 and 12:00 UTC
    
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python company-cron.py
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

